import { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowLeft, Download, ImagePlus, Layers, RotateCcw, Undo2, Upload, WandSparkles } from 'lucide-react'

const MAX = 100
const FILTERS = { none: 'Original', grayscale: 'Grayscale', vivid: 'Vivid', vintage: 'Vintage', cool: 'Cool', warm: 'Warm' }
const RATIOS = { free: null, square: 1, landscape: 16 / 9, portrait: 4 / 5, story: 9 / 16 }

function readImage(file) {
  return new Promise((resolve, reject) => { const image = new Image(); image.onload = () => resolve(image); image.onerror = reject; image.src = URL.createObjectURL(file) })
}
function clamp(value, min, max) { return Math.min(max, Math.max(min, value)) }
function download(blob, name) { const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000) }
function outputName(file, index) { const base = file.name.replace(/\.[^.]+$/, '').replace(/[^a-z0-9_-]/gi, '-'); return `${base || `image-${index + 1}`}-edited.${file.type.includes('jpeg') ? 'jpeg' : 'png'}` }

function renderImage(image, edit, layer) {
  const sourceRatio = image.naturalWidth / image.naturalHeight
  let crop = { ...edit.crop }
  if (edit.ratio !== 'free') {
    const target = RATIOS[edit.ratio]
    if (sourceRatio > target) { crop.width = crop.height * target / sourceRatio } else { crop.height = crop.width * sourceRatio / target }
    crop.x = clamp(crop.x, 0, 1 - crop.width); crop.y = clamp(crop.y, 0, 1 - crop.height)
  }
  const sx = crop.x * image.naturalWidth, sy = crop.y * image.naturalHeight
  const sw = crop.width * image.naturalWidth, sh = crop.height * image.naturalHeight
  const canvas = document.createElement('canvas'); canvas.width = Math.max(1, Math.round(sw)); canvas.height = Math.max(1, Math.round(sh))
  const ctx = canvas.getContext('2d'); ctx.filter = edit.filter === 'grayscale' ? 'grayscale(1)' : edit.filter === 'vivid' ? 'saturate(1.45) contrast(1.08)' : edit.filter === 'vintage' ? 'sepia(.42) saturate(.82) contrast(1.08)' : edit.filter === 'cool' ? 'saturate(1.1) hue-rotate(12deg)' : edit.filter === 'warm' ? 'sepia(.18) saturate(1.2)' : 'none'
  ctx.drawImage(image, sx, sy, sw, sh, 0, 0, canvas.width, canvas.height)
  if (layer) { const stack = Array.isArray(layer) ? layer : [layer]; stack.forEach(item => { ctx.globalAlpha = edit.layerOpacity; ctx.globalCompositeOperation = edit.layerBlend || 'source-over'; ctx.drawImage(item, 0, 0, canvas.width, canvas.height) }); ctx.globalAlpha = 1; ctx.globalCompositeOperation = 'source-over' }
  return new Promise(resolve => canvas.toBlob(resolve, image.src.startsWith('blob:') ? 'image/png' : 'image/png', .94))
}

export default function ImageEditor({ onBack }) {
  const [files, setFiles] = useState([]); const [images, setImages] = useState([]); const [layers, setLayers] = useState([]); const [previewUrl, setPreviewUrl] = useState('')
  const [edit, setEdit] = useState({ ratio: 'free', filter: 'none', crop: { x: 0, y: 0, width: 1, height: 1 }, layerOpacity: .65, layerBlend: 'source-over' })
  const [history, setHistory] = useState([]); const [previews, setPreviews] = useState(true); const [selected, setSelected] = useState(0); const [layer, setLayer] = useState('random'); const input = useRef(null); const layerInput = useRef(null); const cropDrag = useRef(null)
  const current = images[selected]
  const pushEdit = (patch) => { setHistory(h => [...h.slice(-2), edit]); setEdit(e => ({ ...e, ...patch })) }
  const addFiles = async (list) => { const next = Array.from(list).filter(file => ['image/png', 'image/jpeg'].includes(file.type)).slice(0, MAX - files.length); if (!next.length) return; const loaded = await Promise.all(next.map(readImage)); setFiles(f => [...f, ...next]); setImages(i => [...i, ...loaded]); if (!files.length) setSelected(0) }
  const addLayers = async (list) => { const loaded = await Promise.all(Array.from(list).filter(file => ['image/png', 'image/jpeg'].includes(file.type)).map(readImage)); setLayers(l => [...l, ...loaded]) }
  const layerImage = useMemo(() => layers.length ? (layer === 'random' ? [layers[selected % layers.length]] : layers.slice(0, Number(layer) + 1)) : [], [layers, layer, selected])
  const moveLayer = (index, direction) => { const next = index + direction; if (next < 0 || next >= layers.length) return; setHistory(h => [...h.slice(-2), edit]); setLayers(items => { const copy = [...items]; [copy[index], copy[next]] = [copy[next], copy[index]]; return copy }) }
  const startCropDrag = (event, mode = 'move') => { if (!current || edit.ratio !== 'free') return; event.preventDefault(); const rect = event.currentTarget.parentElement.getBoundingClientRect(); cropDrag.current = { mode, startX: event.clientX, startY: event.clientY, rect, crop: { ...edit.crop } }; const move = (moveEvent) => { const drag = cropDrag.current; if (!drag) return; const dx = (moveEvent.clientX - drag.startX) / rect.width; const dy = (moveEvent.clientY - drag.startY) / rect.height; const next = { ...drag.crop }; if (mode === 'move') { next.x = clamp(drag.crop.x + dx, 0, 1 - next.width); next.y = clamp(drag.crop.y + dy, 0, 1 - next.height) } else { next.width = clamp(drag.crop.width + dx, .2, 1 - drag.crop.x); next.height = clamp(drag.crop.height + dy, .2, 1 - drag.crop.y) } setEdit(value => ({ ...value, crop: next })) }; const end = () => { if (cropDrag.current) setHistory(h => [...h.slice(-2), edit]); cropDrag.current = null; window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', end) }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', end) }
  const saveAll = async () => { for (let i = 0; i < files.length; i++) download(await renderImage(images[i], edit, layer === 'random' ? [layers[i % layers.length]] : layers.slice(0, Number(layer) + 1)), outputName(files[i], i)) }
  const cropBox = current ? { left: edit.crop.x * 100, top: edit.crop.y * 100, width: edit.crop.width * 100, height: edit.crop.height * 100 } : null
  useEffect(() => { let active = true; if (!current) { setPreviewUrl(''); return undefined }; renderImage(current, edit, layer === 'random' ? (layers.length ? [layers[selected % layers.length]] : []) : layers.slice(0, Number(layer) + 1)).then(blob => { if (active && blob) setPreviewUrl(URL.createObjectURL(blob)) }); return () => { active = false } }, [current, edit, layer, layers, selected])
  useEffect(() => () => { images.forEach(i => URL.revokeObjectURL(i.src)); if (previewUrl) URL.revokeObjectURL(previewUrl) }, [images, previewUrl])
  const handleDrop = event => { event.preventDefault(); event.stopPropagation(); addFiles(event.dataTransfer.files) }
  const handleDragOver = event => { event.preventDefault(); event.stopPropagation(); event.dataTransfer.dropEffect = 'copy' }
  return <section className="editor-screen" onDrop={handleDrop} onDragOver={handleDragOver} onDragEnter={handleDragOver}>
    <div className="eyebrow"><span className="eyebrow-line" /> IMAGE EDITOR</div>
    <div className="intro-row"><div><h1>Make your batch <em>yours.</em></h1><p className="subtitle">Edit up to 100 PNG or JPEG images locally, then download the finished set.</p></div><button className="back-link" onClick={onBack}><ArrowLeft size={16} /> Choose another action</button></div>
    <div className="editor-toolbar"><button className="go-button" onClick={() => input.current?.click()}><Upload size={16} /> Upload images</button><input ref={input} hidden type="file" accept=".png,.jpg,.jpeg,image/png,image/jpeg" multiple onChange={e => addFiles(e.target.files)} /><span className="editor-count">{files.length} / 100 images</span><button className="secondary-button inline" disabled={!history.length} onClick={() => { const previous = history.at(-1); setHistory(history.slice(0, -1)); setEdit(previous) }}><Undo2 size={15} /> Undo</button><button className="secondary-button inline" disabled={!files.length} onClick={saveAll}><Download size={15} /> Save all</button></div>
    {!files.length ? <div className="editor-empty" onClick={() => input.current?.click()} onDrop={handleDrop} onDragOver={handleDragOver}><ImagePlus size={28} /><strong>Drop up to 100 images here or browse</strong><small>PNG and JPEG only · edits stay in your browser</small></div> : <div className="editor-layout" onDrop={handleDrop} onDragOver={handleDragOver}>
      <aside className="editor-sidebar"><div className="thumb-grid">{images.map((image, i) => <button className={i === selected ? 'thumb active' : 'thumb'} key={i} onClick={() => setSelected(i)}><img src={image.src} /><span>{i + 1}</span></button>)}</div><button className="secondary-button" onClick={() => { setFiles([]); setImages([]); setHistory([]) }}>Clear batch</button></aside>
      <div className="editor-stage"><div className="preview-frame" style={{ aspectRatio: current ? (edit.ratio === 'free' ? `${current.naturalWidth} / ${current.naturalHeight}` : String(RATIOS[edit.ratio])) : undefined }}>{previews && current && <><img src={edit.ratio === 'free' ? current.src : previewUrl || current.src} style={{ filter: edit.ratio === 'free' ? (edit.filter === 'grayscale' ? 'grayscale(1)' : edit.filter === 'vivid' ? 'saturate(1.45) contrast(1.08)' : edit.filter === 'vintage' ? 'sepia(.42) saturate(.82)' : edit.filter === 'cool' ? 'hue-rotate(12deg)' : edit.filter === 'warm' ? 'sepia(.18) saturate(1.2)' : 'none') : 'none' }} />{edit.ratio === 'free' && layerImage.map((item, index) => <img className="preview-layer" key={index} src={item.src} style={{ opacity: edit.layerOpacity, mixBlendMode: edit.layerBlend }} />)}{edit.ratio === 'free' && cropBox && <div className="crop-overlay" onPointerDown={event => startCropDrag(event)} style={{ left: `${cropBox.left}%`, top: `${cropBox.top}%`, width: `${cropBox.width}%`, height: `${cropBox.height}%` }}><button className="crop-handle" onPointerDown={event => { event.stopPropagation(); startCropDrag(event, 'resize') }} aria-label="Resize crop" /></div>}</>}</div><div className="preview-toggle"><button className={previews ? 'active' : ''} onClick={() => setPreviews(true)}>Preview all</button><button className={!previews ? 'active' : ''} onClick={() => setPreviews(false)}>Hide previews</button></div></div>
      <div className="editor-controls"><label>Crop method<select value={edit.ratio} onChange={e => pushEdit({ ratio: e.target.value })}>{Object.keys(RATIOS).map(r => <option key={r} value={r}>{r === 'free' ? 'Free / GUI crop' : r[0].toUpperCase() + r.slice(1)}</option>)}</select></label>{edit.ratio === 'free' && <p className="crop-help">Drag the crop box to move it. Drag the lower-right handle to resize.</p>}<label>Colour effect<select value={edit.filter} onChange={e => pushEdit({ filter: e.target.value })}>{Object.entries(FILTERS).map(([value, name]) => <option key={value} value={value}>{name}</option>)}</select></label><div className="layer-heading"><Layers size={15} /> Random top layer <button onClick={() => layerInput.current?.click()}><WandSparkles size={14} /> Add layers</button><input ref={layerInput} hidden type="file" accept=".png,.jpg,.jpeg,image/png,image/jpeg" multiple onChange={e => addLayers(e.target.files)} /></div>{layers.length > 0 && <><select value={layer} onChange={e => { setHistory(h => [...h.slice(-2), edit]); setLayer(e.target.value) }}><option value="random">Random layer per image</option>{layers.map((_, i) => <option value={i} key={i}>Layer {i + 1}</option>)}</select><div className="layer-list">{layers.map((_, i) => <div className="layer-row" key={i}><span>Layer {i + 1}</span><button onClick={() => moveLayer(i, -1)} disabled={i === 0}>↑</button><button onClick={() => moveLayer(i, 1)} disabled={i === layers.length - 1}>↓</button><button onClick={() => { setHistory(h => [...h.slice(-2), edit]); setLayers(items => items.filter((__, index) => index !== i)) }}>×</button></div>)}</div><label>Layer opacity <input type="range" min="0" max="1" step=".01" value={edit.layerOpacity} onChange={e => pushEdit({ layerOpacity: Number(e.target.value) })} /></label></>}<p className="editor-note"><RotateCcw size={14} /> Every control applies to the full batch. Undo keeps the last three edits.</p></div>
    </div>}
  </section>
}
